version: '3.8'

services:
  wordpress:
    image: wordpress:php8.3-apache
    build:
      context: dockerfiles
      dockerfile: wordpress.dockerfile
    container_name: estudo-wp
    volumes:
      - ./wordpress:/var/www/html
      - ./dockerfiles/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      WORDPRESS_DEBUG: 1
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: wordpress
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
      XDEBUG_SESSION: start
    depends_on:
      - db
    ports:
      - 8080:80

  db:
    image: mysql:8.0.36
    container_name: estudo-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  wordpress:
    driver: local
  mysqldata:
    driver: local